---
kind: pipeline
type: ssh
name: bookhunter

server:
    host:
        from_secret: host
    user:
        from_secret: username
    ssh_key:
        from_secret: ssh_key
steps:
    - name: build
      environment:
          BASE_DIR: /data/book/calibre/down-book
          BOOKHUNTER_BIN: /data/book/bookhunter
      commands:
          - $BOOKHUNTER_BIN tianlang -e -f epub -f zip -r --source lanzou -t 4 -d $BASE_DIR/tianlang -t 2 --ratelimit 120