version: 2
project_name: calibre-api

before:
    hooks:
        - go mod tidy

builds:
    - id: calibre-api
      binary: calibre-api
      flags:
        - -gcflags=all=-l -B
        - -ldflags=-s -w
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - "386"
          - amd64
          - arm64
      ignore:
          - goos: darwin
            goarch: "386"
          - goos: windows
            goarch: arm64

checksum:
    name_template: 'checksums.txt'

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^web:'
            - '^build:'

archives:
    - id: calibre-api
      builds:
          - calibre-api
      format: tar.gz
      wrap_in_directory: "true"
      format_overrides:
          - goos: windows
            format: zip

release:
    draft: true

snapshot:
  version_template: "{{ incminor .Version }}-next"
