address: :8080
debug: false
staticDir: "/app/static"
tmpDir: ".files"
content:
  server: https://lib.pve.icu
search:
  host: http://127.0.0.1:7700
  apikey:
  index: books
metadata:
  doubanurl: http://192.168.2.236:8085
