address: :8080
debug: true
staticDir: "/app/static"
tmpDir: ".files"
content:
  server: https://lib.pve.icu
search:
  host: http://127.0.0.1:7700
  apikey:
  index: books
metadata:
  doubanurl: https://book.douban.com/
