address: :8080
debug: false
calibre:
  library: /book/calibre
  fixpath:
    from: /data/book/calibre/library
    to:
search:
  host: http://127.0.0.1:7700
  apikey:
  index: books
storage:
  use: webdav
  tmpdir: ".files"
  webdav:
    host: http://xxxxxx
    user: xxxxx
    password: "xxxxxxxxxxxxx"
    path: /book/calibre/library
