#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 jianyun8023 <https://zhaojianyun.com>
#

name: Build Dev Images
on:
  workflow_dispatch:
  push:
env:
  IMAGE_NAME: calibre-api
  VERSION: "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set VERSION for release
        if: github.event_name == 'release'
        run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
