#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 jianyun8023 <https://zhaojianyun.com>
#

name: Build Web Dev Images
on:
  workflow_dispatch:
  push:
    paths:
      - 'web-next/**'
      - '.github/workflows/build-web-dev.yaml'

jobs:
  build-and-push:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      image_name: calibre-web
      context: ./web-next
      file: ./web-next/Dockerfile
      build_version: dev
      tags_config: |
        type=raw,value=dev
    secrets: inherit
