#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 jianyun8023 <https://zhaojianyun.com>
#

name: Build Calibre-Web Images
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      image_name: calibre-web
      context: ./web-next
      file: ./web-next/Dockerfile
      build_version: ${{ github.event.release.tag_name || '0.0.1' }}
      tags_config: |
        type=raw,value=${{ github.event.release.tag_name || '0.0.1' }}
        type=raw,value=latest
    secrets: inherit
